# Generated by Django 2.2.7 on 2019-11-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_sighting',
            fields=[
                ('Shift', models.CharField(blank=True, choices=[('PM', 'PM'), ('AM', 'AM')], max_length=2, null=True)),
                ('Latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Unique_Squirrel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=20)),
                ('Primary_Fur_Color', models.CharField(choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=20)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above_Ground', 'Above_Ground')], max_length=20)),
                ('Specific_Location', models.CharField(max_length=50)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(max_length=50)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
