# Generated by Django 2.2.7 on 2019-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above_Ground', 'Above_Ground')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Specific_Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
