# Generated by Django 2.2.7 on 2019-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191128_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Running',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
