# Generated by Django 2.2.7 on 2019-11-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191128_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Approaches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Chasing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Climbing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Eating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Foraging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Indifferent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Kuks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Moans',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Quaas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Runs_from',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Tail_flags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Tail_twitches',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
