# Generated by Django 2.2.7 on 2019-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191128_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_sighting',
            name='Unique_Squirrel_ID',
        ),
        migrations.AddField(
            model_name='new_sighting',
            name='id',
            field=models.AutoField(auto_created=True, default=9, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
