# Generated by Django 2.2.7 on 2019-11-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191128_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sighting',
            name='Unique_Squirrel_ID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
