# Generated by Django 2.2.7 on 2019-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_new_sighting_unique_squirrel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Unique_Squirrel_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
