# Generated by Django 2.2.7 on 2019-11-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0008_auto_20191128_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sighting',
            name='Hectare',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='new_sighting',
            name='Hectare_Squirrel_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
