# Generated by Django 2.2.7 on 2019-11-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0009_auto_20191129_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
