# Generated by Django 2.2.7 on 2019-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0010_auto_20191129_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
