# Generated by Django 2.2.7 on 2019-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0011_auto_20191130_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sighting',
            name='Approaches',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Chasing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Climbing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Eating',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Foraging',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Indifferent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Kuks',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Latitude',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Longitude',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Moans',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Quaas',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Running',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Runs_from',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Tail_flags',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Tail_twitches',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='new_sighting',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
